### PR TITLE
Add non-virtual navigation properties, a base namespace and class

### PR DESCRIPTION
**Pull request by rsouthworth**
Add options to add non-virtual navigation properties, specifying a base namespace for the POCO classes and also a base class for POCO classes.

### CODE REVIEW

**Comment by moh-hassan** [comment]
@rsouthworth, Welcome and thanks for the contribution.
POCO clases are generated from OData metadata document. POCO should reflect the real model because it's used in the client-side for loading data using HTTP service.

For the features you suggest:
**Inheritnes option -i:**
You set all classes to inherit from one base class/interface , which doesn't fit the real model. The inheritances should be per Class.  
Currently the inheritances  is extracted  from the XML Metadata (not user defined, but the Type Attribute of the metadata).

**Eager option:**
Eager loading isn't supported by the current version of OData and this may lead to DoS of eagerly loaded service.
$expand string query is used in the URL for eager loading. Have a look to: http://stackoverflow.com/questions/10318609/eager-loading-with-odata

I think these options may violate the specs of OData.
If you have a reasonable suggestion for adding these features, let me know.
Thanks for contribution.

**Comment by rsouthworth** [comment]
Hi.

Thank you for taking the time to reply.

I am using the 'inheritance' option so that I can use the POCO classes with
a common primary key via applying a common interface or a base class. This
is more convenient for my use case than working with key attributes.

I am using the 'eager' option so I can build an object graph of returned
values easily. I can see from your article link that eager loading isn't
supported. Thank you. I tend to use $select and $expand to return the
hierarchy of values I need. Perhaps this just needs renaming.

All of the options are being used so that the classes can be automatically
generated without any further manual processing, which helps with automated
builds, continuous integration etc.

rgds
Richard

**Comment by moh-hassan** [comment]
Hi,
Thanks for your suggestions.
For inheritance, the option  "-i MyBaseClass,MyInterface",  will generate ALL classes in the model in this way (all classes inherit from one and only one baseClass/interface):

      public class Region : MyBaseClass,MyInterface
	{
	   // properties 
	}

	public class Shipper : MyBaseClass,MyInterface
	{
	    // properties
	}
	
	.......
	
       public class AnyClass : MyBaseClass,MyInterface
	{
	    //..........
	}
	
Do you intend to set all classes to inherit from one and only one  baseClass/interface?
	
Or may be the inheritance is per class?
Something like this - (taking into account the limitation of the command-line parser of Mapping Properties to Options and complexity of implementation )
	
	-i "Region:MyRegionBaseClass,MyInterface ; Shipper:MyShipperBaseClass,MyInterface"
	
This means:
 "Region" class inherit from "MyRegionBaseClass,MyInterface"
 "Shipper" class inherit from "MyShipperBaseClass,MyInterface" 

The generated classes are like this:
	
	 public class Region : MyRegionBaseClass,MyInterface
	{
	   // properties 
	}

	public class Shipper : MyShipperBaseClass,MyInterface
	{
	    // properties
	}
	
	
	What is the best  approach  to go?

**Comment by rsouthworth** [comment]
Hi.



Thank you for outlining your approach.I can see where it would be useful.
Partial classes are also another idea.



The single base class and/or interface for me solves the particular issue I
am working on; identifying them all as 'entities' with a fixed primary key
name. There are a few hundred entities, so providing mapping details via a
command line isn't really practical for my particular case. You will see
the same sort of approach in the Microsoft OData T4 template client
generated classes. e.g.

public partial class School :
global::Microsoft.OData.Client.BaseEntityType,
global::System.ComponentModel.INotifyPropertyChanged



I don't think your approach or mine is right or wrong, they are just
solving different use cases.



rgds

Richard

**Comment by moh-hassan** [comment]
Hi,
Thank you for  clearfication, and I agree for your concerns.
I'll fetch your PR locally and prepare for the  next version including your features.
 
Thank you! :)

**Comment by rsouthworth** [comment]
Hi.

Cool. That's great. Thanks again for your time.

rgds
Richard

**Comment by rsouthworth** [comment]
Hi.

Great. Thank you for your work with this project, I have found it very
useful when working with client classes based on an OData service's
metadata.

rgds
Richard

**Comment by moh-hassan** [comment]
Hi,
Thank you very much for  supporting and Encouragement.  
It's a pleasure for me to add extra features. Let's be in touch for any future suggestions you can find it useful for the project.
You can try the new release 2.1.0 including your PR#2 that i uploaded in nuget: [OData2Poco.CommandLine 2.1.0 ]( https://www.nuget.org/packages/OData2Poco.CommandLine/2.1.0 )
Best Regards

**Comment by moh-hassan** [comment]
Hi rsouthworth,
I have puplished a new version 2.2.0 to support converting Name to camelCase/PasCase and Adding JsonProperty as described in the Feature  request Issue[ #1 Feature Request: Camel-to-Pascal Support](url) 
Give it a try. 
Best Regards,
Moh. Hassan

**Pull request merged**
