### PR TITLE
Enabled support for partial classes.

### PR DESCRIPTION
**Pull request by triplebeta**
Added commandline option and extra setting to enable generating partial classes.
Seemed like this was already partially in place in the implementation but there was no option to enable it.

### CODE REVIEW

**Comment by moh-hassan** [comment]
Welcome to odata2poco project
PR will be merged in the next release.
What about: if partial keyword for classes to be added by default without options in the commandline?

**Comment by triplebeta** [comment]
Thanks, would be fine with me!

Another great change would be when the actual generated code would be in a
T4 template so that it's easy to change. Especially if it would be possible
to externalities the templates.

I did this in one of my projects on Github (the hard way, later I found it
could be done easier :).

Op 30 apr. 2017 14:51 schreef "Mohamed Hassan" <notifications@github.com>:

**Comment by moh-hassan** [comment]
Thanks for response.
Can i know some details about the externalities the templates :)

**Comment by triplebeta** [comment]
Sure! If you download my SpecByExample project you will see how I did it.
It is a VS project template,  with a custom tool, item template and VS
editor that together deliver an experience for quickly setting up 3
projects to automate testing a website using Selenium and Specflow.

About externalizing the templates, in short: I created a Visual Studio item
template that installs the T4 templates in a project. The custom tool (like
the o2p.exe) looks in the solution directory for a specific directory of
those T4 templates. When it finds them, it uses those templates instead of
the ones that were included in the custom tool as embedded resources.

Good luck!
Jeroen

Op 30 apr. 2017 5:18 p.m. schreef "Mohamed Hassan" <notifications@github.com
>:

Thanks for response.
Can i know some details about the externalities the templates :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/moh-hassan/odata2poco/pull/4#issuecomment-298234912>,
or mute the thread

**Pull request closed without merging**
